version: '2'
services:
  registration-service:
    build: ../registrationService
    restart: always
    ports:
      - "8083:8083"
    environment:
      ENV: DEV
      PORT: 8083
      QUEUE_SERVICE_URL: http://queue-service:8082

  queue-service:
    build: ../queueService
    restart: always
    ports:
      - "8082:8082"
    environment:
      ENV: DEV
      PORT: 8082
      ACCOUNT_SERVICE_URL: http://account-service:8080
      LOOKUP_SERVICE_URL: http://lookup-service:8081

  account-service:
    build: ../accountService
    restart: always
    ports:
      - "8080:8080"
    environment:
      ENV: DEV
      PORT: 8080

  lookup-service:
    build: ../lookupService
    restart: always
    ports:
      - "8081:8081"
    environment:
      ENV: DEV
      PORT: 8081
